config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    :registrations => "users/registrations"
  }

  root to: "tasks#index"
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  get 'calendar', to: 'tasks#calendar'
  resources :tasks do
    get :assign, on: :member
    
  end
  
  resources :users, only:[:show]
  get 'categories/list' => 'categories#list'
  resources :categories 
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end  
  post '/tasks/:id/edit', to: 'tasks#update'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  validates :title, :start_time,  :status, presence: true
  validates :category_id, presence: { message: 'を選択してください。' }
  paginates_per 12
  scope :latest, -> {order(id: :desc)}
  scope :old, -> {order(id: :asc)}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy assign done ]
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :destroy, :update]
  before_action :advance_category
  

  def index
    @tasks  = Task.all.page(params[:page]).order(id: :desc).per(12)
    @tasks_done = Task.where.not(start_time:nil)
    if params[:latest]
      @tasks = Task.latest.page(params[:page]).order(id: :desc).per(12)
    elsif params[:old]
      @tasks = Task.old.page(params[:page]).order(id: :desc).per(12)
    else
      @Tasks = Task.all.page(params[:page]).order(id: :desc).per(12)
    end
  end

  def show
    @task = Task.find_by(id: params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path } 
        format.js 
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Task was successfully created." }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
    flash[:success] = "削除に成功しました。"
  end

  def edit 
    unless @task.user == current_user
      redirect_to  new_task_path
    end
  end


  def update
    if @task.user != current_user
      redirect_to  root_path
    else
      if @task.update(task_params)
        redirect_to request.referer
      else
        flash.now[:danger] = '編集に失敗しました。'
        render request.referer
      end
    end
  end

  def assign
  end

  def done
    @today = Date.today 
    @task.update(status: "完了", start_time: @today) 
    redirect_to request.referer
  end
  def calendar
    @tasks  = Task.reorder('id DESC')
    task_count = Task.all.count
  end
  

  private
    
  def set_task
    @task = Task.find(params[:id])
  end
  def task_params
    params.require(:task).permit(:title, :content, :status, :start_time, :user_id, :category_id)
  end
  def baria_user
    unless Task.find(params[:id]).user.id.to_i == current_user.id
        redirect_to tasks_path(current_user)
    end
  end
  
  
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/.filtter_by_category.html.erb
<% @tasks.each do |task| %>
  <div class="workspace-task-content <%= "finish" if task.status == '完了'  %>  <%= Time.current >= task.start_time ? 'expired' : 'required' %>">
  <ul class="work-task-edit" id='<%= task.id %>'>
    <li class="work-task-edit-title">
      <%= link_to task.title.truncate(26), task, class: 'work-task-edit-title-link' %>
      <% if task.user == current_user %>
        <span class="workspace-link">
          <% unless task.status == '完了'    %>
            <%= button_to '完了', done_path(task.id), method: :post %>
          <% end %>
          <%= link_to "/tasks/#{task.id}/edit", :method => :get, :remote => true do %>
            <%= image_tag '鉛筆アイコン8.png' %>
          <% end %>
        </span>
      <% end %>
    </li>
    <li class="work-task-edit-username">担当者：<%= task.user.name %></li>
  </ul>
  </div>

<% end %>

app/views/tasks/_filter_by_category.html.erb
<% @tasks.each do |task| %>
  <div class="workspace-task-content <%= "finish" if task.status == '完了'  %>  <%= Time.current >= task.start_time ? 'expired' : 'required' %>">
  <ul class="work-task-edit" id='<%= task.id %>'>
    <li class="work-task-edit-title">
      <%= link_to task.title.truncate(26), task, class: 'work-task-edit-title-link' %>
      <% if task.user == current_user %>
        <span class="workspace-link">
          <% unless task.status == '完了' %>
            <%= button_to '完了', done_path(task.id), method: :post %>
          <% end %>
          <%= link_to "/tasks/#{task.id}/edit", :method => :get, :remote => true do %>
            <%= image_tag 'enpitsu.png' %>
          <% end %>
        </span>
      <% end %>
    </li>
    <li class="work-task-edit-username">担当者：<%= task.user.name %></li>
  </ul>
  </div>

<% end %>

app/views/tasks/_task-form.html.erb
<%= form_with(model: @task, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div>
    <%= f.label :タイトル %><br>
    <%= f.text_field :title, autofocus: true %>
  </div>
  <div>
    <%= f.label :内容 %><br>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.label :状況 %><br>
    <div class="status-in">
    <%= f.radio_button :status, :"未対応" %>
    <%= f.label :status, "未対応", value: :"未対応" %>
    <%= f.radio_button :status, :"対応中" %>
    <%= f.label :status, "対応中", value: :"対応中" %>
    </div>
  </div>
  <div class="deadline-select">
    <%= f.label :期限 %><br>
    <%= f.datetime_select :start_time, class: 'form-control' %>
    <%= f.datetime_field :start_time, class: 'form-control' %>
  </div>
  <div class="project-select">
    <%= f.label  "ワークスペース" %><%= link_to "（ワークスペース追加はこちら）", new_category_path, target: :_blank, rel: "noopener noreferrer" %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "選択してください"} %>
  </div>
  <div class="task-form-actions">
    <%= f.submit "登録する" %>
    <%= link_to '一覧へ戻る', tasks_path %>
  </div>
<% end %>

app/views/tasks/_task_show.html.erb
<table id="task-show-about">
    <tr>
      <th>タイトル</th>
      <th class="task-show-about-th2"><%= @task.title %></th> 
    </tr>
    <tr>
      <th>内容</th>
      <th class="task-show-about-th2"><%= simple_format(@task.content)%></th> 
    </tr>
    <tr>
      <th>期限</th>
      <th class="task-show-about-th2"><%= @task.start_time.strftime('%Y年%m月%d日') %></th> 
    </tr>
    <tr>
      <th>担当者</th>
      <th class="task-show-about-th2"><%= @task.user.name %></th> 
    </tr>
    <tr>
      <th>ステータス</th>
      <th class="task-show-about-th2"><%= @task.status %></th> 
    </tr>
  </table>

app/views/tasks/_test.html.erb
<% @tasks.each do |task| %>
  <ul>
  <li><%= task.title.truncate(32) %></li>
  </ul>

<% end %>

app/views/tasks/assign.html.erb
<div class="container">  
  <div id="assign">
    <h2 class="page_title">アサイン</h2>
    <div id="assign-form"> 
      <%= simple_form_for @task do |f| %>
        <p>アサインするユーザーを選択</p>
        <div id="assign-form-inside">
          <%= f.input :user_id, collection: User.all %>
          <p id="assign-submit">
            <%= f.button :submit, 'アサイン' %>
          </p>
        </div>
      <% end %>
    </div>
    <%= render "task_show", task: @task %>
  </div>
</div>

app/views/tasks/calendar.html.erb
<%= month_calendar events: @tasks do |date, tasks| %>
  <div id="upper">
    <p id="upper-other1"><%= date.day %></p>
    <p id="upper-other2"><%= tasks.count %>件</p>
  </div>
  <% tasks.each do |task| %>
    <div id="under"><%= link_to task.title.truncate(14), task %></div>
  <% end %>
<% end %>

app/views/tasks/create.js.erb
$('#workspace-newtask').html('<ul id="<%= @task.id %>"><li class="work-task-edit-title"><%= link_to @task.title.truncate(32), @task, class: "work-task-edit-title-link" %><span class="workspace-link"><% unless @task.status == "完了" %><%= button_to "完了", done_path(@task.id), method: :post %><% end %><%= link_to edit_task_path(@task), :method => :get, :remote => true do %><%= image_tag 'enpitsu.png' %><% end %></span></li><li class="work-task-edit-username">担当者：<%= @task.user.name %></li></ul>');

app/views/tasks/edit.html.erb
<div class="container">  
  <div class="task-form">
    <h2 class="page_title">タスク編集</h2>
    <%= render 'tasks/task-form' %>
  </div>
</div>

app/views/tasks/edit.js.erb
$('#<%= @task.id %>').html('<div><%= form_for("/tasks/#{@task.id}/edit") do %><div class="work-task-edit-form1"><input name="task[title]" value="<%= @task.title %>"></input></div><div class="work-task-edit-form2"><textarea name="task[content]"><%= @task.content %></textarea></div><div class="work-task-edit-action"><input type="submit" value="保存"><%=link_to '戻る', :back, class:'back' %></div><% end %></div>')

app/views/tasks/index.html.erb
<div class="gg">
  <%= link_to image_tag("/assets/calendar"), calendar_path, class: "gg-img"  %>
  <div class="sort">
    <%= link_to '新しい順', tasks_path(latest: "true") %>
    <%= link_to '古い順', tasks_path(old: "true") %>
  </div>
</div>

<div id="task-index">
  <% @tasks.each do |task| %>
    <div class="task-panel <%= "finish" if task.status == '完了'  %>  <%= Time.current >= task.start_time ? 'expired' : 'required' %>">
      <h4><%= task.title %></h4>
      <div id="task-panel-content">
        <% if task.status == '完了' %>
          <p>完了日：<%= task.start_time.strftime('%Y年%m月%d日') %><span>完了</span></p>
        <% else %>
          <p>
            期限：<%= task.start_time.strftime('%Y年%m月%d日') %>
            <% if Time.current >= task.start_time %>
              <span>期限切</span>
            <% else %>
              <span>期限内</span>
           <% end %>
          </p>
        <% end %>
        <p>担当者：<%= task.user.name %></p>
        <p>ステータス：<%= task.status %></p>
        <div class="task-action">
          <%= link_to '詳細', task, class: 'task-action1' %>
          <% if task.user == current_user %>
            <%= link_to '編集', edit_task_path(task), class: 'task-action2' %>
            <%= button_to "削除", task, data: { confirm: "削除して大丈夫ですか?" }, method: :delete %>
            <% unless task.status == '完了'  %>
              <%= button_to '完了', done_path(task.id), method: :post %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div id="home-pagination">
  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<div class="container">  
  <div class="task-form">
    <h2 class="page_title">新規タスク</h2>
    <%= render 'tasks/task-form' %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">  
  <div id="task_show">
    <h2 class="page_title">タスク詳細</h2> 
    <%= render "task_show", task: @task %>
  
    <div id="task-action-show">
      <div class="task-action">
        <%= link_to '一覧へ戻る', tasks_path, class: 'task-show-action1' %>
        <% if @task.user == current_user %>
          <%= link_to '編集', edit_task_path(@task) %>
          <%= button_to "削除", @task, data: { confirm: "削除して大丈夫ですか?" }, method: :delete %>
          <%= link_to 'アサイン', assign_task_path(@task) %>
          <% unless @task.status == '完了'  %>
            <%= button_to '完了', done_path(@task.id), method: :post %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>