config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    :registrations => "users/registrations"
  }

  root to: "tasks#index"
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  get 'calendar', to: 'tasks#calendar'
  resources :tasks do
    get :assign, on: :member
    
  end
  
  resources :users, only:[:show]
  get 'categories/list' => 'categories#list'
  resources :categories 
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end  
  post '/tasks/:id/edit', to: 'tasks#update'
end

app/views/layouts/_categorymenu.html.erb
<% if controller.controller_name == 'tasks' or controller.controller_name == 'categories' %>
<div id="header-2">
  <div class="dropdown">
    <button class="dropdown_btn" id="dropdown__btn">ワークスペースを選択</button>
    <div class="dropdown_body">
      <ul class="dropdown_list">
        <% @categories.first(10).each do |category| %>
          <li class="dropdown_item"><%= link_to category.name, categories_path(category_id: category.id) %></li>
        <% end %>
        <li class="dropdown_item_other">
          <%= link_to "ワークスペース一覧", categories_list_path %>
          <%= link_to 'ワークスペース追加', new_category_path %>
        </li>
      </ul>
    </div>
  </div>
  <div>
    <ul class="menu">
      <li>
        <% if user_signed_in? %>
          <p><%= current_user.name %><span>さん</span></p>
        <% end %>
          <ul class="menu_content">
            <li><%= link_to 'ユーザー設定', edit_user_registration_path, class: "nav-link" %></li>
            <li><%= link_to 'ログアウト', users_sign_out_path, data: { confirm: "ログアウトしますか?" }, method: :delete, class: "nav-link" %></li> 
          </ul>
      </li>
    </ul>
	</div>
</div>
<% end %>
  

	

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <script>
    setTimeout(function() {
      $('.alert').fadeOut();
    }, 5000);
  </script>
<% end %> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-sm">
  <a class="navbar-brand" href="/">タスク管理アプリ</a>
  <ul class="navbar-nav">
    <% if user_signed_in? %> 
      <li><%= link_to 'タスク一覧', tasks_path, class: "nav-link" %></li>
      <li><%= link_to "マイタスク", user_path(current_user.id),  class: "nav-link" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "nav-link" %></li>
      <li><%= link_to "新規登録", new_registration_path(resource_name), class: "nav-link" %></li>
    <% end %>
  </ul>
  <div class="hamburger-menu">
    <input type="checkbox" id="menu-check">
    <label for="menu-check" class="menu-bar"><span></span></label>
    <div class="menu-content">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to 'タスク一覧', tasks_path %></li>
          <li><%= link_to 'ユーザー設定', edit_user_registration_path %></li>
          <li><%= link_to "マイタスク", user_path(current_user.id) %></li>
          <li><%= link_to 'ログアウト', users_sign_out_path, data: { confirm: "ログアウトしますか?" }, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to "新規登録", new_registration_path(resource_name) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if user_signed_in? %>
      <%= render 'layouts/categorymenu' %>
    <% end %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    

  </body>
</html>